[phases]
  setup = "dotnet-sdk"  # Cài đặt .NET SDK
  install = "dotnet restore"  # Chạy dotnet restore để phục hồi các gói
  build = "dotnet publish --no-restore -c Release -o out"  # Build ứng dụng
  start = "dotnet out/WebEcommerce.dll"  # Chạy ứng dụng sau khi build

[variables]
  ASPNETCORE_URLS = "http://0.0.0.0:5000"  # Cấu hình URL cho ứng dụng
